version: '3.3'

services:
    rdtclient:
        image: pukabyte/rdtclient:seed
        container_name: rdtclient
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /opt/rdtclient/data/downloads:/data/downloads
            - /opt/rdtclient/data/db:/data/db
	    - /mnt:/mnt
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'
        healthcheck:
            test: curl --fail http://localhost:6500 || exit 1
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 30s
